PATH_TO_DATASET = "/home/letzzbuild/Desktop/customer_segmentation/Backend/customer_segmentation/dataset/Customer_data.csv"
FROM_EMAIL = "****************"
TO_EMAIL = "******************"
LOGIN_EMAIL = "youremailaddress"
LOGIN_EMAIL_PASSWORD = "yourpassword"
