# Generated by Django 3.2 on 2021-06-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('deal_id', models.AutoField(primary_key=True, serialize=False)),
                ('deal_name', models.CharField(max_length=100)),
                ('discount', models.ImageField(upload_to='')),
                ('category', models.CharField(max_length=50)),
                ('discount_price', models.IntegerField()),
                ('original_price', models.IntegerField()),
            ],
            options={
                'db_table': 'deals',
            },
        ),
    ]
