# Generated by Django 3.2 on 2021-06-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals',
            name='product_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
